version: '3'

services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - poke-data:/data/db
    ports:
       - 27019:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD= ${MONGO_PASSWORD}
    command: ["--auth"]

  mongo-express:
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME= ${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD= ${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=db
    ports:
      - 8087:8081
    restart: always       

  # pokemon-app:
  #   depends_on:
  #     - db
  #     - mongo-express
  #   image: klerith/pokemon-nest-app:1.0.0
  #   ports:
  #     - 3005:3000
  #   environment:
  #     MONGODB: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:27019
  #     DB_NAME: ${MONGO_DB_NAME}
  #   restart: always  
    
    
volumes:
  poke-data:
    external: false
